/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowlogin (void);
GtkWidget* create_rby_util (void);
GtkWidget* create_is_agentbv (void);
GtkWidget* create_zd_election (void);
GtkWidget* create_md_reclamation (void);
GtkWidget* create_aa_listeelec (void);
GtkWidget* create_aa_vote (void);
GtkWidget* create_mo_bureau_de_vote (void);
