/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *windowlogin;
  GtkWidget *rby_util;
  GtkWidget *is_agentbv;
  GtkWidget *zd_election;
  GtkWidget *md_reclamation;
  GtkWidget *aa_listeelec;
  GtkWidget *aa_vote;
  GtkWidget *mo_bureau_de_vote;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  windowlogin = create_windowlogin ();
  gtk_widget_show (windowlogin);
  rby_util = create_rby_util ();
  gtk_widget_show (rby_util);
  is_agentbv = create_is_agentbv ();
  gtk_widget_show (is_agentbv);
  zd_election = create_zd_election ();
  gtk_widget_show (zd_election);
  md_reclamation = create_md_reclamation ();
  gtk_widget_show (md_reclamation);
  aa_listeelec = create_aa_listeelec ();
  gtk_widget_show (aa_listeelec);
  aa_vote = create_aa_vote ();
  gtk_widget_show (aa_vote);
  mo_bureau_de_vote = create_mo_bureau_de_vote ();
  gtk_widget_show (mo_bureau_de_vote);

  gtk_main ();
  return 0;
}

